default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  url: <%= ENV['postgresql://jumpnews_user:Ub86lvyEkNjDJnfNnv1TjEvtjRCwqfom@dpg-ctkubh9opnds7382jk2g-a/jumpnews'] %>

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
